### ISSUE TITLE
key not found "rspec"

### ISSUE THREAD

**Issue by javpaw** [jonleighton/spring-commands-rspec#24]
Hi I'm getting the following error when trying to run
$ bin/rspec

and getting the following error:
spring-1.1.3/lib/spring/commands.rb:20:in `fetch': key not found: "rspec" (KeyError)

the problem is in this function (in spring/commands.rb)

  def self.command(name)
    commands.fetch name
  end

so rspec is not registered in commands for some reason.
I followed all the steps to install, don't know what to do.
I'm using spring 1.1.3, spring-commands-rspec 1.0.2, rspec-rails 3.1.0 and rspec-core 3.1.5

thanks.

**Comment by tbuehlmann** [comment]
@javpaw, does stopping Spring solve your problem?

**Comment by oliverbarnes** [comment]
sup @jonleighton :) how's it going?

I'm having this problem too, and restarting spring doesn't solve it. Using spring 1.3.3, rails 3.2.21, ruby 2.1.5

**Comment by aliou** [comment]
Was having the same problem, stoping spring seems to fix it.

**Comment by oliverbarnes** [comment]
not fixing it for me, though :/

**Comment by jonleighton** [comment]
Hi @oliverbarnes, I'm afraid Rails 3.2 is no longer officially supported in Spring 1.3.

I'm also going to close this bug because I think it mostly relates to people installing spring-commands-rspec and then not realising they need to stop spring before the new command will be available. That problem is solved in Spring 1.3 so I think this bug can be closed.

If you are continuing to have issued under Rails 4+ / Spring 1.3 then please open a new bug.

**Comment by sungwoncho** [comment]
I had the same issue with Rails (4.2.1), spring (1.3.6), and spring-commands-rspec (1.0.4). I was able to resolve it by stopping spring and starting it again.

**Comment by A5308Y** [comment]
Having the same issue with spring (1.3.4), spring-commands-rspec (1.0.4), Rails (4.2.0). Stopping spring solved it for me as well.
